apps/accounts/urls.py
# -*- encoding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.detail, name='detail'),
    url(r'^password/$', views.password_change, name='password_change'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^register/$', views.create, name='create'),
]

headstart/urls.py
# -*- encoding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import include, url
from django.contrib import admin
from two_factor.urls import core as two_factor_patterns
from two_factor.views import ProfileView

from contrib.two_factor import DisableView
from .views import IndexView


two_factor_profile = [
    url(r'^account/two_factor/$', ProfileView.as_view(), name='profile'),
    url(r'^account/two_factor/disable/$', DisableView.as_view(), name='disable'),
]

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^account/', include('apps.accounts.urls', namespace='accounts')),
    url(r'', include(two_factor_patterns + two_factor_profile, namespace='two_factor')),
    url(r'^admin/', include(admin.site.urls)),
]

apps/accounts/models.py
# -*- encoding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin

from .managers import UserManager


@python_2_unicode_compatible
class User(AbstractBaseUser, PermissionsMixin):
    """
    Basic admin-compatible user model
    with email and password.

    """
    email = models.EmailField(_('email'), unique=True)
    is_active = models.BooleanField(_('active'), default=True)
    created = models.DateTimeField(_('date joined'), auto_now_add=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')
        ordering = ['email']

    def __str__(self):
        return self.email

    @property
    def is_staff(self):
        return self.is_superuser

    def get_short_name(self):
        return self.email

apps/accounts/forms.py
# -*- encoding: utf-8 -*-
from __future__ import unicode_literals

from django import forms
from django.utils.translation import ugettext_lazy as _
from django.contrib import auth

from .models import User


class UserCreateForm(forms.ModelForm):
    """
    Create a new user account.

    """
    password = forms.CharField(label=_('Password'))

    class Meta:
        model = User
        fields = ['email']

    def save(self, commit=True):
        self.user = super(UserCreateForm, self).save(commit=False)
        self.user.set_password(self.cleaned_data['password'])

        if commit:
            self.user.save()
        return self.user


class PasswordChangeForm(forms.Form):
    """
    Verify the user's current password and set a new one.

    """
    ERRORS = {
        'current_password': _('Current password is not correct.'),
    }

    current_password = forms.CharField(label=_('Current password'), widget=forms.PasswordInput)
    password = forms.CharField(label=_('New password'))

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super(PasswordChangeForm, self).__init__(*args, **kwargs)

    def clean_current_password(self):
        password = self.cleaned_data['current_password']
        if not self.user.check_password(password):
            raise forms.ValidationError(self.ERRORS['current_password'])
        return True

    def save(self):
        password = self.cleaned_data['password']
        self.user.set_password(password)
        self.user.save()

apps/accounts/views.py
# -*- encoding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import redirect
from django.core.urlresolvers import reverse_lazy
from django.utils.translation import ugettext_lazy as _
from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required

from vanilla import DetailView, CreateView, FormView

from .forms import UserCreateForm, PasswordChangeForm
from .models import User


def logout(request):
    auth.logout(request)
    messages.info(request, _('You have been logged out.'))
    return redirect('index')


class PasswordMixin(object):
    """
    Keep the session logged in after setting a user's password.

    """
    def get_success_message(self):
        if not self.success_message:
            raise NotImplementedError('Implement get_success_message()')
        return self.success_message

    def form_valid(self, form):
        form.save()
        user = auth.authenticate(username=form.user.email,
                                 password=form.cleaned_data['password'])

        if user is None:
            messages.error(request, _('Authentication failed!'))
            return redirect('accounts:login')

        messages.success(self.request, self.get_success_message())
        auth.login(self.request, user)
        return redirect('accounts:detail')


class UserCreateView(PasswordMixin, CreateView):
    """
    This view will attempt to create a new user.

    If email verification is active, no user will be created.
    Instead, a signed link will be sent via email; clicking
    this link will automatically create a verified user account.

    """
    model = User
    form_class = UserCreateForm
    template_name_suffix = '_register'

    success_message = _('Thank you for registering!')

create = UserCreateView.as_view()


class UserDetailView(DetailView):
    """
    View your account details.

    """
    name = 'user_detail'
    model = User

    def get_object(self):
        return self.request.user

detail = login_required(UserDetailView.as_view())


class PasswordChangeView(PasswordMixin, FormView):
    """
    Let users change their password.

    """
    name = 'password_change'
    form_class = PasswordChangeForm
    template_name = 'accounts/change_password.html'

    success_message = _('Password changed!')

    def get_form(self, *args, **kwargs):
        kwargs.update({'user': self.request.user})
        return super(PasswordChangeView, self).get_form(*args, **kwargs)

password_change = login_required(PasswordChangeView.as_view())

apps/accounts/templates/accounts/base.html
{% extends 'base.html' %}
{% load i18n %}

{% block main %}
  <div class="row">
    <h1 class="small-12 columns">{% block page_title %}headstart{% endblock %}</h1>
    <div class="small-4 columns">
      <ul class="side-nav">
        <li class="{% if view.name == 'user_detail' %}active{% endif %}">
          <a href="{% url 'accounts:detail' %}">
            {% trans 'Account details' %}
          </a>
        </li>
        <li class="{% if view.name == 'password_change' %}active{% endif %}">
          <a href="{% url 'accounts:password_change' %}">
            {% trans 'Change password' %}
          </a>
        </li>
        <li class="{% if request.resolver_match.namespace == 'two_factor' %}active{% endif %}">
          <a href="{% url 'two_factor:profile' %}">
            {% trans 'Two-factor authentication' %}
          </a>
        </li>
      </ul>
    </div>
    <div class="small-8 columns">
      {% block content %}{% endblock %}
    </div>
  </div>
{% endblock %}

apps/accounts/templates/accounts/change_password.html
{% extends 'accounts/base.html' %}
{% load i18n sniplates %}

{% block title %}{% trans 'Change password' %} | {{ block.super }}{% endblock %}
{% block page_title %}{% trans 'Change password' %}{% endblock %}

{% block content %}

  <form method="post">
    {% load_widgets form='widgets/foundation.html' %}
    {% csrf_token %}

    {% form_field form.current_password %}
    {% form_field form.password %}

    {% nested_widget 'form:Content' %}
      <p>{% trans 'Changing your password will log you out of all other open browser sessions.' %}</p>
    {% endnested %}

    {% trans 'Change password' as label %}
    {% widget 'form:Submit' label=label %}
  </form>

{% endblock %}

apps/accounts/templates/accounts/user_detail.html
{% extends 'accounts/base.html' %}
{% load i18n %}

{% block title %}{% trans 'My account' %} | {{ block.super }}{% endblock %}
{% block page_title %}{% trans 'My account' %}{% endblock %}

{% block content %}

  <dl>
    <dt>{% trans 'Email' %}</dt>
    <dd>{{ user.email }}</dd>
  </dl>

{% endblock %}

apps/accounts/templates/accounts/user_register.html
{% extends 'base.html' %}
{% load sniplates %}

{% block title %}{% trans 'Register' %} | {{ block.super }}{% endblock %}
{% block page_title %}{% trans 'Register' %}{% endblock %}

{% block content %}

  <form method="post">
    {% load_widgets form='widgets/foundation.html' %}
    {% csrf_token %}

    {% form_field form.email placeholder='john.doe@example.com' %}
    {% trans 'We will show you what you type so you can be sure there are no typos.' as password_placeholder }
    {% form_field form.password placeholder=password_placeholder %}

    {% trans 'Register' as label %}
    {% trans 'Login' as secondary_label %}
    {% url 'two_factor:login' as url %}
    {% widget 'form:Submit' label=label secondary=secondary_label secondary_url=url %}
  </form>

{% endblock %}